### ISSUE TITLE
Support for Attachments?

### ISSUE THREAD

**Issue by t-oster** [gessnerfl/fake-smtp-server#10]
Is there any planned support for attachments? Right now only the source is visible, but I cannot e.g. download an attachment.

**Comment by gessnerfl** [comment]
Sounds like a good idea ;) 
I think it shouldn't be too complicated to add this. I will try to add this feature soon

**Comment by gessnerfl** [comment]
Support is now available with version 1.0.0

**Comment by t-oster** [comment]
That was quick! Works as intended, thank you.

**Comment by Depact** [comment]
I use 2.0.2. I don't see emails attachments in tomcat hosted on port 8080.

**Comment by gessnerfl** [comment]
@Depact created #193 to fix this issue

**Comment by gessnerfl** [comment]
@Depact Issue fixed in version 2.0.3
