### ISSUE TITLE
unable to execute latest jar

### ISSUE THREAD

**Issue by panwarab** [gessnerfl/fake-smtp-server#109]
I used the following issue ( https://github.com/gessnerfl/fake-smtp-server/issues/41 ) to create jar file.

When I am trying to execute the created jar, it fails with the below error:

```
Error: Could not find or load main class fake-smtp-server-1.10.5-SNAPSHOT.jar
Caused by: java.lang.ClassNotFoundException: fake-smtp-server-1.10.5-SNAPSHOT.jar
```

can't seem to understand what is missing since I have tried multiple approaches suggested online for gradle and spring boot project. Any help on this one, it's blocking in creating the source code. Thanks.

**Comment by gessnerfl** [comment]
@panwarab fakesmtp server requires at least java 11. Can you please share more details on your system setup

**Comment by panwarab** [comment]
Hi,

My system has both Java 8 and Java 11. I am trying to execute the code via
directly referencing java11.exe fake-smtp-snapshot.jar

This invocation is being done over cygwin terminal.

**Comment by gessnerfl** [comment]
@panwarab  Java 8 is not working as at least Java 11 is required.
I tried the latest release (https://github.com/gessnerfl/fake-smtp-server/releases/download/1.10.4/fake-smtp-server-1.10.4.jar) with Java 11 and Java 17 on my Mac and for both it is working fine.

I guess there is something wrong with your Java installation.
Please make sure you compile the application using Java 11+ and also run the application with a properly installed Java 11+

**Comment by gessnerfl** [comment]
Closing the output after more than 3 months of inactivity
