### ISSUE TITLE
Managing used memory by docker container

### ISSUE THREAD

**Issue by smuda** [gessnerfl/fake-smtp-server#12]
Hi!
When limiting memory for the docker container the fake-smtp-server does not seem to adopt accordingly.

To verify, run the following command to limit the container to 512MB and print the MaxHeapSize:
```
docker run --rm -it -m 512M --entrypoint "java" gessnerfl/fake-smtp-server -XX:+PrintFlagsFinal -version | grep -i MaxHeapSize
    uintx MaxHeapSize                              := 788529152                           {product}
```
As you can see, the allocated MaxHeapSize is roughly 788 MiB, which is slightly more than the 512MB allowed.

This can be mitigated by changing the startup command such as:
```
docker run --rm -it -m 512M --entrypoint "java" gessnerfl/fake-smtp-server -XX:+PrintFlagsFinal -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -version | grep -i MaxHeapSize
    uintx MaxHeapSize                              := 134217728                           {product}
```
As you can see, the MaxHeapSize is now roughly a forth of the available memory.

According to  [https://blogs.oracle.com/java-platform-group/java-se-support-for-docker-cpu-and-memory-limits](https://blogs.oracle.com/java-platform-group/java-se-support-for-docker-cpu-and-memory-limits) the UseCGroupMemoryLimitForHeap is on by default in java 8u131 and later. The current version of java in the container seems to be 1.8.0_171 so the simplest mitigation could be to simply update java in the container. 

Probably a rebuild of the image would do the trick.

**Comment by smuda** [comment]
I created a pull request, [#13](https://github.com/gessnerfl/fake-smtp-server/pull/13) to force the java version.
I'm a noob with gradle so when I build using gradle the output is called fake-smtp-server-1.1.0-SNAPSHOT.jar. However, the Dockerfile expects the filename to be fake-smtp-server.jar. Perhaps you could look into that?

**Comment by gessnerfl** [comment]
Version 1.0.2 is now available with the Java 8 u 181 to fix this issue. I will work on a Java 11 release in the next days
