### ISSUE TITLE
Security issue with snakeyaml

### ISSUE THREAD

**Issue by fguiet** [gessnerfl/fake-smtp-server#124]
Hi,

Can you update the snakeyaml library as it is vulnerable to this security issue:

![image](https://user-images.githubusercontent.com/13849639/226963169-64de3602-2671-42ad-922e-789952708fec.png)

Thank
fred

**Comment by gessnerfl** [comment]
It is already fixed in the master branch. However I'm currently working on a new major release and want to incorporate another change first

**Comment by gessnerfl** [comment]
I will need some time as I currently rework UI. I guess I will need one or two more weeks.

**Comment by gessnerfl** [comment]
Should be fixed now with version 2.0.0. Can you please cross check.

**Comment by gessnerfl** [comment]
Issue fixed in latest version. Closing after several months of no response
