### ISSUE TITLE
Error starting v2.0.0 with Java 11

### ISSUE THREAD

**Issue by rstewart-inl** [gessnerfl/fake-smtp-server#143]
<img width="1027" alt="image" src="https://user-images.githubusercontent.com/52046212/232598509-8c98a587-d8a8-45c5-8118-376e5556cdcb.png">

Same error on a different system with Java version listed as:
```
java version "11.0.18" 2023-01-17 LTS
Java (TM) SE Runtime Environment 18.9 (build 11.0.18+9-LTS-195)
Java Hotspot (TM) 64-Bit Server VM 18.9 (build 11.0.18+9-LTS-195, mixed mode)
```

**Comment by etidahouse** [comment]
You must use java 17 version

https://en.wikipedia.org/wiki/Java_class_file#General_layout

**Comment by we3geeks** [comment]
@etidahouse README.md indicates Java 11 is required.

**Comment by gessnerfl** [comment]
@rstewart-inl @we3geeks 
Indeed java 17 is required starting with version 2.0.0. I missed to update README.md. Sorry for that.
Version 2.0.0 is based on Spring Boot 3.0.0 which requires at least Java 17. For security reasons I try to keep the project up to date an make sure to not use outdated 3rd party libraries.

**Comment by rstewart-inl** [comment]
@gessnerfl Thanks for the follow-up and the clarification. We are currently version-locked at Java 11 (still actively supported by Oracle through Sep 2023 and OpenJDK through Sep 2024) based on other software where I'm using this. I'll stay with 1.10.4 for now.

It might also be a good idea to include mention of this change in dependency in the release notes for 2.0.0.
