### ISSUE TITLE
implement "allowedRecipentAddresses" configuration in app.yml

### ISSUE THREAD

**Issue by NileshKSingh** [gessnerfl/fake-smtp-server#154]
There is "blockedRecipientAddresses" in the yml configuration:

```
blockedRecipientAddresses:
    - blocked@example.com
    - foo@eample.com
```

Do we have similar config, where we can only **allowed only** specific email address ?

The above is a requirement for me, because in public cloud when i was running this SMTP service, I was getting some spam mails - hacker were using some port scanner to find vulnerabilities.

**Comment by gessnerfl** [comment]
@NileshKSingh the application is intended for development/testing purposes. The feature would be possible. However considering your use case I would strongly recommend you to consider other security measures such as not exposing the application to public or at least to implement IP allow lists.

**Comment by NileshKSingh** [comment]
Thanks [gessnerfl](https://github.com/gessnerfl) for your suggestion. I can quickly check 'IP allow lists' settings with my hosting-provider
