### ISSUE TITLE
Authenticate does not properly authenticate

### ISSUE THREAD

**Issue by pat-lego** [gessnerfl/fake-smtp-server#16]
When users have .auth() or (.userName() and .password()) enabled on the @Rule for the SMTP server the authentication mechanism of the mock server throws a Null Pointer Error.

Debugged it and saw that the error occurs at the following line: 
`if (clientInput.trim().equals(AUTH_CANCEL_COMMAND))` in the AuthCommand class returns null instead of the an empty string.

This is stopping users from properly testing the SMTP server with Authentication.

**Comment by gessnerfl** [comment]
@pat-lego I tried to reproduce the issue but without success. Basically `if (clientInput.trim().equals(AUTH_CANCEL_COMMAND))` is part of the smtp server library https://github.com/voodoodyne/subethasmtp which I used in this project.

I created a new branch with integration tests. Can you please provide more details how the servers are configured and also a bit more details about the client setup.

**Comment by pat-lego** [comment]
I have the following in my Class:

@ClassRule
	public static FakeSmtpRule smtpServer = new FakeSmtpRule(ServerConfiguration.create().port(2525).charset("UTF-8").userName("someusername").password("somepassword"));

I use the javax.mail library in the OpenJDK 64 bit Java 11 to send emails to the fake SMTP server and when I try to send emails with that username and password I get a NullPointerError.

Let me know if you require more information to reproduce this error.

**Comment by gessnerfl** [comment]
@pat-lego It would be great to get some more details about the FakeSmtpRule and the ServerConfiguration. What is it doing specifically? Can you maybe share some code snippets. This could help me to reproduce the issue.

**Comment by pat-lego** [comment]
Email Client:

```

**Comment by pat-lego** [comment]
@gessnerfl That line of code is what is creating the

**Comment by pat-lego** [comment]
```@ClassRule
public static FakeSmtpRule smtpServer = new FakeSmtpRule(ServerConfiguration.create().port(2525).charset("UTF-8").relayDomains("localhost").userName("uottawa.outreach@gmail.com").password("uottawaTestTest");`

**Comment by gessnerfl** [comment]
@pat-lego I do use login. The MailSender provides both options. However I have the feeling that you mix the projects. I do not see how this project relates to the implementation in https://github.com/sleroy/fakesmtp-junit-runner. I think it is not even used there. 
The mentioned project also uses https://github.com/voodoodyne/subethasmtp natively. So I guess this is the right place for the issue.
Or am I wrong?

**Comment by pat-lego** [comment]
You are correct I did mix up the projects but I am still able to get the error. Now that being said I am not too sure if it is the GitHub project that is not sending in the data correctly to the https://github.com/voodoodyne/subethasmtp project or if it is a bug within the core project.

My guess based off of your testing is that it's how the other project is communicating with the main library. I  will log a ticket on the other github project.

I apologize for the mistake.

Thank you for all your help.

On Dec 12, 2018 2:04 AM, Florian Gessner <notifications@github.com> wrote:

@pat-lego<https://github.com/pat-lego> I do use login. The MailSender provides both options. However I have the feeling that you mix the projects. I do not see how this project relates to the implementation in https://github.com/sleroy/fakesmtp-junit-runner. I think it is not even used there.
The mentioned project also uses https://github.com/voodoodyne/subethasmtp natively. So I guess this is the right place for the issue.
Or am I wrong?

**Comment by jabbadev** [comment]
@pat-lego excuse me Patrique i have the same error in my code.

have you fix the problem ? 

can you share with me some information about the solution ?
