### ISSUE TITLE
Only 100 results 

### ISSUE THREAD

**Issue by jessec** [gessnerfl/fake-smtp-server#195]
I can see only 100 emails any idea how I can increase this number?

![image](https://github.com/gessnerfl/fake-smtp-server/assets/528312/777f4b6b-4557-40bb-a1fb-69561b525785)

**Comment by gessnerfl** [comment]
@jessec: as described in the documentation, the service stores only a limited number of emails to avoid excessive memory usage.

> The server store a configurable maximum number of emails. If the maximum number of emails is exceeded old emails will be deleted to avoid that the system consumes too much memory.

The default value is **100** but you can change it via the configuration:

```yaml
fakesmtp:
  persistence:
    maxNumberEmails: 100
```

**Comment by jessec** [comment]
Should I also change a setting for the UI? I can still not page beyond page 10. 


![image](https://github.com/gessnerfl/fake-smtp-server/assets/528312/f6f618d4-6328-4a31-8173-2cf59b7fb731)

**Comment by jessec** [comment]
Not sure what setting did it or maybe something went wrong compiling the new changes, but it is working now. Thanks

![image](https://github.com/gessnerfl/fake-smtp-server/assets/528312/bc5336b6-a057-4dff-82a7-e2ef09536fb9)

**Comment by gessnerfl** [comment]
There is no configuration needed for the UI. The configuration parameter mentioned above effects the persistence. This means that the system will automatically delete old emails when the given limit is exceeded.
