### ISSUE TITLE
[feature-request] consider proxy mode

### ISSUE THREAD

**Issue by bilak** [gessnerfl/fake-smtp-server#29]
Hi,
at first thanks for this application, it helped me during development.
Would you consider functionality, where it will be possible to store mails inside fake-smtp-server as it's possible to store now and also send messages via configured smtp server? So basically fake-smtp-server will serve as some kind of proxy where it would be possible:
* to store mails inside it
* allow to send those mails further via configured server

thanks

**Comment by gessnerfl** [comment]
@bilak basically I think this would be possible to implement without too much effort as Spring Boot is already providing good support for sending emails. The configuration could be reused from Spring Boot and proxing could be just added as an additional configuration option.

However it would be good if you could explain in more detail what is the background of this feature request?

**Comment by bilak** [comment]
Background is for example: when I have some templating system and tester/developer is testing/developing some template, the system is connected to live group emails. But sometimes it needs to be changed little bit, so to ease development I can stop sending those changed emails for a while and if template is fixed/changed I can again send emails to the group.

**Comment by gessnerfl** [comment]
@bilak the feature is now available with version 1.5.0.
Looking forward to get feedback from your side!
