### ISSUE TITLE
Management API does not find any Mails

### ISSUE THREAD

**Issue by primus852** [gessnerfl/fake-smtp-server#31]
When running the FakeSMTP, receiving mails via WebUI works like a charm. However, when I check `http://localhost:5081` I only get this:

```
{
  "timestamp":"2020-07-15T13:06:25.760+0000",
  "status":404,
  "error":"Not Found",
  "message":"No message available",
  "path":"/"
}
```

Is there something I am missing or is there a bug?

**Comment by gessnerfl** [comment]
@primus852 port 8081 is the management port which is basically used for monitoring purposes and health checks. It does not provide any API for managing mails.
The management API is based on Spring Boot actuator. On the path `/actuator` you can get an overview of all available endpoints. More details about spring boot actuator can be found in the official Spring Boot Documentation: https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#production-ready.

**Comment by smuda** [comment]
@primus852 Have a look at PR #32 where there is an API for retrieving emails.

**Comment by gessnerfl** [comment]
Closing the ticket after one month of activity. Rest controller is available on server port
