### ISSUE TITLE
Question: Why are all properties in the OpenAPI specification optional?

### ISSUE THREAD

**Issue by muehmar** [gessnerfl/fake-smtp-server#318]
We are using the fake smtp server to perform integration test, i.e. check if certain events in our application actually send emails. To automate this, we use the API of the server to fetch and check the emails. We use a Java generator which creates DTO's from the schema components in the openapi. The generator reflects also the specification of optional/required and nullability. Thus it generates getters with Optional<T> as return value in case the properties are optional which seems to be the case for every property in the specification. Is this intentionally? 

I could either check every property before accessing it, if its already there (which could be avoided in case the specification tells which property must exist) or I could just avoid all checks but then I dont know which property is really optional and may be absent. What was the intention here or how should one access the API?

**Comment by gessnerfl** [comment]
@muehmar Not sure why this is the case. The documentation is generated by springdoc-openapi. I need to dig deeper into it.

**Comment by gessnerfl** [comment]
@muehmar the issue should be fixed in version 2.1.5.

**Comment by gessnerfl** [comment]
please reopen the ticket if the issue persists.

**Comment by muehmar** [comment]
I'll have a look, thank you and happy new year :-)
