### ISSUE TITLE
Exception thrown on initial start

### ISSUE THREAD

**Issue by amirAtWork** [gessnerfl/fake-smtp-server#327]
Hi,

We have updated to the latest version and have found that every time the app is started in the morning, we get errors in the output. A subsequent restart fixes this but something is clearly wrong/broken?

Attached is the output from this morning  with first output and then second startup.
[second-startup.txt](https://github.com/gessnerfl/fake-smtp-server/files/13335088/second-startup.txt)
[startup.txt](https://github.com/gessnerfl/fake-smtp-server/files/13335089/startup.txt)

**Comment by gessnerfl** [comment]
@amirAtWork it seems that the startup of the services takes longer and because of this the background job to delete emails is triggered before the system is being initialized. I will adjust the initial delay to fix this issue.

**Comment by gessnerfl** [comment]
@amirAtWork 
The issue should be fixed now with version 2.2.0. Please cross check and reopen the ticket if the issue persists.
