### ISSUE TITLE
STARTTLS closes the SSLSocket after creation

### ISSUE THREAD

**Issue by danielabeledo** [gessnerfl/fake-smtp-server#373]
Hi, it seems you are wrapping the creation of the SSLSocket with a try-with-resources.

https://github.com/gessnerfl/fake-smtp-server/blob/main/src/main/java/de/gessnerfl/fakesmtp/smtp/command/StartTLSCommand.java#L42

SSLSocketImpl implements Autocloseable so the TLS socket closes before the STARTTLS command finishes

**How to reproduce**
Java version 21

Running application with self-signed certificate

`openssl s_client -starttls smtp -connect <HOST:PORT> -crlf -CAfile certificate.pem`

**Remediation**

Running the application without wrapping the socket creation with try-with-resources solves the issue

**Comment by gessnerfl** [comment]
@danielabeledo  you are right. Issue is fixed with version 2.2.0

**Comment by gessnerfl** [comment]
Can you please cross check and reopen if the issue persists

**Comment by danielabeledo** [comment]
Yeah, looks fine to me now - thanks for the quick turnaround
