### ISSUE TITLE
creating JAR

### ISSUE THREAD

**Issue by PhantomLord72** [gessnerfl/fake-smtp-server#41]
How can I build an executable JAR in IntelliJ Idea? to run as java -jar .... ?
I am stuck in the screen and don't know what to specify:
![image](https://user-images.githubusercontent.com/44055542/122559906-37590f80-d040-11eb-8c96-154f3bafb5db.png)

**Comment by gessnerfl** [comment]
@PhantomLord72 : FakeSmtpServer is based on Spring boot. It is using Gradle as a build system. To create a executable jar you can run the gradle build using the included Gradle Wrapper from the console using the command:

Unix/MacOS:
`./gradlew clean build`

Windows:
`gradlew.bat clean build`

The resulting executable jar including sources and javadoc can be found in `./build/libs`.

**Comment by gessnerfl** [comment]
Closing Issue after no response for more than 3months

**Comment by panwarab** [comment]
why not simply post a .jar as part of release itself?
