### ISSUE TITLE
Question: how is built the gessnerfl/fake-smtp-server image on Docker Hub?

### ISSUE THREAD

**Issue by mxmlnglt** [gessnerfl/fake-smtp-server#421]
Hi,

All the code seems open-source and available at https://github.com/gessnerfl/fake-smtp-server but I can't find/understand how/where is built the image we can find on Docker Hub.
Can you make it more explicit please?

Thank you.

**Comment by gessnerfl** [comment]
Exactly, fake-smtp-server is using Jib (https://github.com/GoogleContainerTools/jib) to build and push the docker images.

**Comment by mxmlnglt** [comment]
OK, thanks for the details; I'm not keen on Gradle so didn't think it would be part of the build file.
