### ISSUE TITLE
"Embedded" mode support

### ISSUE THREAD

**Issue by marceloverdijk** [gessnerfl/fake-smtp-server#47]
Would it be possible to run this embedded in an existing Spring Boot application?

Similar as one e.g. uses the embedded H2 console in development mode.
Like adding a fake-smtp-starter to a project and enable it only for de dev profile.

**Comment by gessnerfl** [comment]
Hi @marceloverdijk,

this is currently not supported and would require a major change on the project. Basically I would have to split the application into a library which can be embedded into a spring boot application and the spring boot application itself.

I currently do not have plans to support this. I also do not fully understand the use case. Isn't it easier to just run it as an additional microservice in the dev profile/landscape? Or are you working on a standalone/monolithic application?

**Comment by marceloverdijk** [comment]
Indeed a standalone application in dev mode.

But no problem and thx for quick feedback!
