### ISSUE TITLE
Allow Emails sent with  TLSv1.2

### ISSUE THREAD

**Issue by chinzzz** [gessnerfl/fake-smtp-server#489]
Is there a configuration I need to change to allow emails sent with TLSv1.2? Currently, emails with TLSv1.2 are not reflecting/reaching our server. Looks like the server is not accepting email with TLS. I am using fake-smtp-server version 2.1.4.

**Comment by chinzzz** [comment]
@gessnerfl, apologies for the late response. We are still doing some investigations but so far the paths are leading to the server certificate. That configuration you mentioned will be very helpful and might actually fix the issue.

**Comment by gessnerfl** [comment]
@chinzzz I added an improved support for TLS with version 2.3.0. You can now configure the keystore used for TLS. When providing keystore, TLS is enabled and can be configured to be mandatory.

See also https://github.com/gessnerfl/fake-smtp-server?tab=readme-ov-file#tls
