### ISSUE TITLE
Content-type type/subtype should be case insensitive

### ISSUE THREAD

**Issue by FejfarKamil** [gessnerfl/fake-smtp-server#51]
According to https://datatracker.ietf.org/doc/html/rfc1341, Content-type: type/subtype, type and subtype should be case insensitive, so https://github.com/gessnerfl/fake-smtp-server/blob/master/src/main/java/de/gessnerfl/fakesmtp/model/ContentType.java does not work for e.g. text/PLAIN.

**Comment by gessnerfl** [comment]
@FejfarKamil makes sense. Thanks for your contribution
