### ISSUE TITLE
Regarding logging

### ISSUE THREAD

**Issue by BigCaber** [gessnerfl/fake-smtp-server#522]
Hi,

I could not find logging for the application on disk, does this application save the logs on disk ?

**Comment by gessnerfl** [comment]
By default the application logs to stdout only. If you want to activate logging to a file you can activate this in the configuration file or via environment variables. See also (https://docs.spring.io/spring-boot/reference/features/logging.html)

**Comment by gessnerfl** [comment]
@BigCaber I hope this was helpful. Please reopen the ticket in case further help is needed
