### ISSUE TITLE
Sunset on jcenter

### ISSUE THREAD

**Issue by smuda** [gessnerfl/fake-smtp-server#53]
fake-smtp-server uses jcenter as the repository. As [jcenter has announced sunset](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/), perhaps changing to mavenCentral would be a good thing?

build.gradle:
`repositories { jcenter() }`

**Comment by gessnerfl** [comment]
@smuda thanks for the hint. Will migrate to maven central

**Comment by gessnerfl** [comment]
switchted to maven central with PR #55
