### ISSUE TITLE
Re-building fake-smtp-server in offline environment

### ISSUE THREAD

**Issue by smuda** [gessnerfl/fake-smtp-server#54]
I'm currently setting up an offline build of fake-smtp-server for use within that secured environment and I've found a few issues that is problematic. I've described what I've found so far below and if you are interested I'll create a pull request.

1. The Dockerfile depends on the filename from the build being `build/libs/fake-smtp-server-$APP_VERSION.jar` but if I build in i a folder that is not named `fake-smtp-server` that assumption is not valid. Setting the jar baseName to fake-smtp-server works nicely though.

```
jar {
	baseName 'fake-smtp-server'
}
```

2. Since the version is already set by you during release I needed a way to specify the version, bypassing the automatic version increment with a parameter. A small change in build.gradle that should not affect you fixes that:

```
project.version = findProperty 'projectVersion' ?: scmVersion.version
```

3. Since docker hub is inaccessible during build, using amazoncorretto:11.0.14-alpine3.15 doesn't work so I needed a way to specify the base image. That way we could also use the internal hardened image where we have more control. When not using the build-arg argument, the default is still amazoncorretto:11.0.14-alpine3.15:

```
ARG BASE_IMAGE=amazoncorretto:11.0.14-alpine3.15
FROM ${BASE_IMAGE}
```

**Comment by gessnerfl** [comment]
@smuda I incorporated the proposed changes into the code with some slight adjustments. The changes are already merge into master branch and released with version 1.8.5.

Can you please cross check.

**Comment by smuda** [comment]
Thank you! I'll verify your changes when I get back at work on tuesday.

**Comment by smuda** [comment]
It worked nicely, thank you!
