### ISSUE TITLE
Providing a container build for linux/arm64 architecture

### ISSUE THREAD

**Issue by StefanSchubert** [gessnerfl/fake-smtp-server#63]
Hi there,

first of all thanks for this contribution :-)  I use the fakesmtp server for my private projects here on github for a long time.
Unfortunately I just switched my notebook which is now running on an ARM cpu architecture. I could deal with it by replacing using docker desktop with colima, but this x64 emulation lacks some performance.

Would it be possible for you to provide a multi arch build for the docker container (using dockers buildx plugin), such that all ARM users will find a fit on docker hub? This would be great.

For now I will lookup a different fakesmtp on dockerhub which supports ARM as well.

THX and have a nice weekend!
Stefan

**Comment by gessnerfl** [comment]
@StefanSchubert: Something I had in mind as well.

**Comment by gessnerfl** [comment]
ARM64 images are released with version 1.9.0. Can you please cross check?

**Comment by StefanSchubert** [comment]
Works as a charm. The docker specialities required with ARM64 architecture can bee seen here: https://github.com/StefanSchubert/sabi/tree/sabi-115/devops/sabi_docker_sdk

Many thanks for providing it so quick :)
