### ISSUE TITLE
Images not shown for HTML-Template emails

### ISSUE THREAD

**Issue by MarioMatschgi** [gessnerfl/fake-smtp-server#84]
We send HTML-Emails from a C# backend and discovered, that the images are not being displayed in the Fake SMTP Server's UI

This is what the emails look like in the UI:
![image](https://user-images.githubusercontent.com/46848943/185096984-4fd1ffa2-cad6-4d33-a938-ccfa793f10f4.png)

This is the content of the mail-tabs-content div on the Fake SMTP Server UI:
![image](https://user-images.githubusercontent.com/46848943/185097178-9530b7c9-bc0e-46bb-a885-d623f8112b72.png)

As you can see, the images have a contentID, as indicated by the "cid:" in the src attribute of the image. 

If i have a look at the "Raw" tab in the UI, you can see that the images are sent correctly with the email:
![image](https://user-images.githubusercontent.com/46848943/185097481-4a3ef44d-9d5b-4b23-ba4c-f889674b1c19.png)

Hope this helps,
if you need any more information, feel free to contact me :)

**Comment by MarioMatschgi** [comment]
> Hi @MarioMatschgi ,
> I'm able to reproduce the issue. Need to think about how I can adopt this such as that the image is properly embedded.

Great! Again, thank you so much - your work is really appreciated!
Hope you have a great day ❤️

**Comment by gessnerfl** [comment]
@MarioMatschgi this should be fixed with version 1.10.0 which is now available

**Comment by MarioMatschgi** [comment]
> @MarioMatschgi this should be fixed with version 1.10.0 which is now available

Wow, thank you so much!
I will try it when I get the time to do so :)

You're awesome, hope you have a great day!

**Comment by MarioMatschgi** [comment]
Hello :)

Great news! The images are now displayed correctly. However now there is a different issue.

The content of the tab named "HTML" has a height of 0, so nothing actually gets  shown:
![image](https://user-images.githubusercontent.com/46848943/188891208-4e9420dd-12a6-4660-8856-e2279299430f.png)

I had to manually set a height to verify that the images are being loaded:
![image](https://user-images.githubusercontent.com/46848943/188891796-e9878a7d-b6fd-49d2-894c-2a9e9a1a5709.png)

The tab "Raw" works correctly though :)

If you need any more information, i will reply ASAP :)

Have a great day!

**Comment by gessnerfl** [comment]
@MarioMatschgi  Can you please check again with version 1.10.1

**Comment by MarioMatschgi** [comment]
> @MarioMatschgi  Can you please check again with version 1.10.1

My teammates tested it and it seems to be working fine!

Again, thank you so much for your efforts ❤️
