### ISSUE TITLE
management.port seems unused

### ISSUE THREAD

**Issue by giorgiosironi** [gessnerfl/fake-smtp-server#9]
This configuration
```
docker run -p 2525:25 -p 5080:5080 -p 5081:5081 gessnerfl/fake-smtp-server
```
does not allow me to connect to localhost:5081, I wanted to check out what sort of API would be exposed there. The port is listed in the README and the Dockerfile.

**Comment by gessnerfl** [comment]
Can confirm that this is a bug. With the update to Spring Boot 2.0 the configuration option for the management server has been changed but was not adopted in the delivered application.properties file. Will fix this issue right now ;)
