### ISSUE TITLE
StackOverFlow Exception - Could not write JSON: Infinite Recursion

### ISSUE THREAD

**Issue by ddoorn** [gessnerfl/fake-smtp-server#94]
This is something that started happening recently (possibly with a recent version). I'm not entirely sure when because this runs in a container in azure and isn't restarted very often. I started getting errors performing performing API calls (connection was closed). I looked at the logs and found this error. Some emails contain images and thinking that might be related.

![image](https://user-images.githubusercontent.com/11317034/191496496-7b829812-411e-4937-8163-48a8cf367704.png)

**Comment by gessnerfl** [comment]
@ddoorn is it possible to provide a sample email so that I can reproduce the issue

**Comment by ddoorn** [comment]
I don't think I can due to the sensitive information that may be in it since it's for internal testing. I'm not even sure how to generate something else that I could use as a repro.

**Comment by ddoorn** [comment]
This doesn't help at all narrowing things down, but my workaround is to fix the container version to 1.7.1 which was the last hash I could find in the logs prior to it going wrong. It's almost 2 years old, but it unblocks me.

**Comment by gessnerfl** [comment]
@ddoorn checked the stack trace in detail and was able to identify the root cause. I released version 1.10.2 which should fix the issue. Can you please cross check.

**Comment by ddoorn** [comment]
@gessnerfl I can confirm the issue is fixed! Thank you.
